//! Diesel SQL function definitions for the `pgmq` extension.

use diesel::deserialize::FromSql;
use diesel::pg::{Pg, PgValue};
use diesel::prelude::*;
use diesel::sql_types::{Array, BigInt, Integer, Jsonb, Nullable, Text, Timestamptz};

/// Diesel SQL type that can be used as the return type of diesel SQL functions generated by
/// the [`declare_sql_function`] macro.
// Relevant example: https://github.com/diesel-rs/diesel/blob/main/examples/postgres/composite_types/examples/composite2rust_colors.rs
type PgMessage = diesel::sql_types::Record<(
    // msg_id
    BigInt,
    // read_ct
    Integer,
    // enqueued_at
    Timestamptz,
    // last_read_at
    Nullable<Timestamptz>,
    // vt
    Timestamptz,
    // message
    Jsonb,
    // headers
    Nullable<Jsonb>,
)>;

impl<T, H> FromSql<PgMessage, Pg> for crate::Message<T, H>
where
    T: for<'de> serde::Deserialize<'de>,
    H: for<'de> serde::Deserialize<'de>,
{
    fn from_sql(bytes: PgValue) -> diesel::deserialize::Result<Self> {
        let (msg_id, read_ct, enqueued_at, last_read_at, vt, message, headers): (
            _,
            _,
            _,
            _,
            _,
            serde_json::Value,
            Option<serde_json::Value>,
        ) = FromSql::<PgMessage, Pg>::from_sql(bytes)?;

        let headers = if let Some(headers) = headers {
            Some(H::deserialize(headers)?)
        } else {
            None
        };

        Ok(Self {
            msg_id,
            read_ct,
            enqueued_at,
            last_read_at,
            vt,
            message: T::deserialize(message)?,
            headers,
        })
    }
}

type PgListTopicBindingsRow = diesel::sql_types::Record<(
    // pattern
    Text,
    // queue_name
    Text,
    // bound_at
    Timestamptz,
    // compiled_regex
    Text,
)>;

impl FromSql<PgListTopicBindingsRow, Pg> for crate::types::ListTopicBindingsRow {
    fn from_sql(bytes: PgValue) -> diesel::deserialize::Result<Self> {
        let (pattern, queue_name, bound_at, compiled_regex) =
            FromSql::<PgListTopicBindingsRow, Pg>::from_sql(bytes)?;

        Ok(Self {
            pattern,
            queue_name,
            bound_at,
            compiled_regex,
        })
    }
}

type PgSendBatchTopicRow = diesel::sql_types::Record<(
    // queue_name
    Text,
    // msg_id
    BigInt,
)>;

impl FromSql<PgSendBatchTopicRow, Pg> for crate::types::SendBatchTopicRow {
    fn from_sql(bytes: PgValue) -> diesel::deserialize::Result<Self> {
        let (queue_name, msg_id) = FromSql::<PgSendBatchTopicRow, Pg>::from_sql(bytes)?;

        Ok(Self { queue_name, msg_id })
    }
}

#[declare_sql_function]
extern "SQL" {
    #[sql_name = "pgmq.create"]
    fn pgmq_create(queue_name: Text);

    #[sql_name = "pgmq.send"]
    fn pgmq_send(queue_name: Text, msg: Jsonb, headers: Jsonb, delay: Integer) -> BigInt;

    #[sql_name = "pgmq.send_batch"]
    fn pgmq_send_batch(
        queue_name: Text,
        msgs: Array<Jsonb>,
        headers: Nullable<Array<Jsonb>>,
        delay: Integer,
    ) -> BigInt;

    #[sql_name = "pgmq.read"]
    fn pgmq_read(queue_name: Text, vt: Integer, qty: Integer) -> PgMessage;

    #[sql_name = "pgmq.pop"]
    fn pgmq_pop(queue_name: Text, qty: Integer) -> PgMessage;

    #[sql_name = "pgmq.archive"]
    fn pgmq_archive(queue_name: Text, msg_ids: Array<BigInt>) -> BigInt;

    #[sql_name = "pgmq.delete"]
    fn pgmq_delete(queue_name: Text, msg_ids: Array<BigInt>) -> BigInt;

    #[sql_name = "pgmq.set_vt"]
    fn pgmq_set_vt(queue_name: Text, msg_ids: Array<BigInt>, vt: Integer) -> PgMessage;

    #[sql_name = "pgmq.create_fifo_index"]
    fn pgmq_create_fifo_index(queue_name: Text);

    #[sql_name = "pgmq.create_fifo_indexes_all"]
    fn pgmq_create_fifo_indexes_all();

    #[sql_name = "pgmq.read_grouped"]
    fn pgmq_read_grouped(queue_name: Text, vt: Integer, qty: Integer) -> PgMessage;

    #[sql_name = "pgmq.read_grouped_head"]
    fn pgmq_read_grouped_head(queue_name: Text, vt: Integer, qty: Integer) -> PgMessage;

    #[sql_name = "pgmq.read_grouped_rr"]
    fn pgmq_read_grouped_rr(queue_name: Text, vt: Integer, qty: Integer) -> PgMessage;

    #[sql_name = "pgmq.bind_topic"]
    fn pgmq_bind_topic(pattern: Text, queue_name: Text);

    #[sql_name = "pgmq.unbind_topic"]
    fn pgmq_unbind_topic(pattern: Text, queue_name: Text);

    #[sql_name = "pgmq.list_topic_bindings"]
    fn pgmq_list_topic_bindings(queue_name: Text) -> PgListTopicBindingsRow;

    #[sql_name = "pgmq.list_topic_bindings"]
    fn pgmq_list_topic_bindings_all() -> PgListTopicBindingsRow;

    #[sql_name = "pgmq.send_topic"]
    fn pgmq_send_topic(routing_key: Text, msg: Jsonb, headers: Jsonb, delay: Integer) -> Integer;

    #[sql_name = "pgmq.send_batch_topic"]
    fn pgmq_send_batch_topic(
        routing_key: Text,
        msgs: Array<Jsonb>,
        headers: Nullable<Array<Jsonb>>,
        delay: Integer,
    ) -> PgSendBatchTopicRow;
}
