#[cfg(feature = "rust-postgres")]
pub mod postgres;
#[cfg(feature = "tokio-postgres")]
pub mod tokio_postgres;

impl<T, H> TryFrom<::tokio_postgres::Row> for crate::Message<T, H>
where
    T: for<'de> serde::Deserialize<'de>,
    H: for<'de> serde::Deserialize<'de>,
{
    type Error = crate::PgmqError;

    fn try_from(value: ::tokio_postgres::Row) -> Result<Self, Self::Error> {
        let message = T::deserialize(value.try_get::<_, serde_json::Value>("message")?)?;
        let headers =
            if let Some(headers) = value.try_get::<_, Option<serde_json::Value>>("headers")? {
                Some(H::deserialize(headers)?)
            } else {
                None
            };
        Ok(Self {
            msg_id: value.try_get("msg_id")?,
            read_ct: value.try_get("read_ct")?,
            enqueued_at: value.try_get("enqueued_at")?,
            last_read_at: value.try_get("last_read_at")?,
            vt: value.try_get("vt")?,
            message,
            headers,
        })
    }
}

impl TryFrom<::tokio_postgres::Row> for crate::types::ListTopicBindingsRow {
    type Error = ::tokio_postgres::Error;

    fn try_from(value: ::tokio_postgres::Row) -> Result<Self, Self::Error> {
        Ok(Self {
            pattern: value.try_get("pattern")?,
            queue_name: value.try_get("queue_name")?,
            bound_at: value.try_get("bound_at")?,
            compiled_regex: value.try_get("compiled_regex")?,
        })
    }
}

impl TryFrom<::tokio_postgres::Row> for crate::types::SendBatchTopicRow {
    type Error = ::tokio_postgres::Error;

    fn try_from(value: ::tokio_postgres::Row) -> Result<Self, Self::Error> {
        Ok(Self {
            queue_name: value.try_get("queue_name")?,
            msg_id: value.try_get("msg_id")?,
        })
    }
}

type SqlParam<'a> = (&'a (dyn postgres_types::ToSql + Sync), postgres_types::Type);

/// This macro defines all the functions required to implement [`crate::queue::Queue`] for both
/// `postgres` and `tokio-postgres` crates. This is possible because the implementations are
/// nearly identical. The only differences are which connection trait is used, one needs the
/// connection/executor to be `&mut C` and one can be `&C`, and one requires `await`-ing DB results.
///
/// The functions defined by this macro are designed to be used by the [`crate::queue::Queue`]
/// definition generated by the [`crate::queue::macros::impl_queue`] macro.
macro_rules! rust_postgres_functions {
    (
        /// The common connection/executor trait to use to implement all the functions
        $executor_trait:path,
        /// Macro that expands to a reference (either mutable or immutable) of the provided type
        $ref_type:tt,
        /// Macro to transform the result (e.g., either simply use it directly, or perform an `await`)
        $transform_result:tt
    ) => {
        async fn create<C>(
            executor: $ref_type!(C),
            queue_name: crate::types::QueueName<'_>,
        ) -> Result<(), crate::PgmqError>
        where
            C: $executor_trait,
        {
            let params: [crate::queue::rust_postgres::SqlParam; _] =
                [(&*queue_name, postgres_types::Type::TEXT)];
            let result = executor.execute_typed(crate::queue::sql::CREATE, &params);
            $transform_result!(result)?;
            Ok(())
        }

        async fn send<C>(
            executor: $ref_type!(C),
            queue_name: crate::types::QueueName<'_>,
            message: serde_json::Value,
            headers: serde_json::Value,
            delay: crate::types::VisibilityTimeoutOffset,
        ) -> Result<i64, crate::PgmqError>
        where
            C: $executor_trait,
        {
            let params: [crate::queue::rust_postgres::SqlParam; _] = [
                (&*queue_name, postgres_types::Type::TEXT),
                (&message, postgres_types::Type::JSONB),
                (&headers, postgres_types::Type::JSONB),
                (&*delay, postgres_types::Type::INT4),
            ];
            let row = executor.query_typed_one(crate::queue::sql::SEND, &params);
            let row = $transform_result!(row)?;
            Ok(row.try_get(0)?)
        }

        async fn send_batch<C>(
            executor: $ref_type!(C),
            queue_name: crate::types::QueueName<'_>,
            messages: Vec<serde_json::Value>,
            headers: Option<Vec<serde_json::Value>>,
            delay: crate::types::VisibilityTimeoutOffset,
        ) -> Result<Vec<i64>, crate::PgmqError>
        where
            C: $executor_trait,
        {
            let params: [crate::queue::rust_postgres::SqlParam; _] = [
                (&*queue_name, postgres_types::Type::TEXT),
                (&messages, postgres_types::Type::JSONB_ARRAY),
                (&headers, postgres_types::Type::JSONB_ARRAY),
                (&*delay, postgres_types::Type::INT4),
            ];
            let rows = executor.query_typed(crate::queue::sql::SEND_BATCH, &params);
            let rows = $transform_result!(rows)?;
            let rows = rows
                .into_iter()
                .map(|row| row.try_get(0))
                .collect::<Result<Vec<i64>, _>>()?;
            Ok(rows)
        }

        async fn read<C, T, H>(
            executor: $ref_type!(C),
            queue_name: crate::types::QueueName<'_>,
            visibility_timeout: crate::types::VisibilityTimeoutOffset,
            quantity: i32,
        ) -> Result<Vec<crate::Message<T, H>>, crate::PgmqError>
        where
            C: $executor_trait,
            T: for<'de> serde::Deserialize<'de>,
            H: for<'de> serde::Deserialize<'de>,
        {
            read_common(
                executor,
                crate::queue::sql::READ,
                queue_name,
                visibility_timeout,
                quantity,
            )
            .await
        }

        async fn pop<C, T, H>(
            executor: $ref_type!(C),
            queue_name: crate::types::QueueName<'_>,
            quantity: i32,
        ) -> Result<Vec<crate::Message<T, H>>, crate::PgmqError>
        where
            C: $executor_trait,
            T: for<'de> serde::Deserialize<'de>,
            H: for<'de> serde::Deserialize<'de>,
        {
            let params: [crate::queue::rust_postgres::SqlParam; _] = [
                (&*queue_name, postgres_types::Type::TEXT),
                (&quantity, postgres_types::Type::INT4),
            ];
            let rows = executor.query_typed(crate::queue::sql::POP, &params);
            let rows = $transform_result!(rows)?;
            rows.into_iter()
                .map(|row| crate::Message::<T, H>::try_from(row))
                .collect::<Result<Vec<crate::Message<T, H>>, crate::PgmqError>>()
        }

        async fn archive<C>(
            executor: $ref_type!(C),
            queue_name: crate::types::QueueName<'_>,
            msg_ids: &[i64],
        ) -> Result<Vec<i64>, crate::PgmqError>
        where
            C: $executor_trait,
        {
            let params: [crate::queue::rust_postgres::SqlParam; _] = [
                (&*queue_name, postgres_types::Type::TEXT),
                (&msg_ids, postgres_types::Type::INT8_ARRAY),
            ];
            let rows = executor.query_typed(crate::queue::sql::ARCHIVE, &params);
            let rows = $transform_result!(rows)?;
            let rows = rows
                .into_iter()
                .map(|row| row.try_get(0))
                .collect::<Result<Vec<i64>, _>>()?;
            Ok(rows)
        }

        async fn delete<C>(
            executor: $ref_type!(C),
            queue_name: crate::types::QueueName<'_>,
            msg_ids: &[i64],
        ) -> Result<Vec<i64>, crate::PgmqError>
        where
            C: $executor_trait,
        {
            let params: [crate::queue::rust_postgres::SqlParam; _] = [
                (&*queue_name, postgres_types::Type::TEXT),
                (&msg_ids, postgres_types::Type::INT8_ARRAY),
            ];
            let rows = executor.query_typed(crate::queue::sql::DELETE, &params);
            let rows = $transform_result!(rows)?;
            let rows = rows
                .into_iter()
                .map(|row| row.try_get(0))
                .collect::<Result<Vec<i64>, _>>()?;
            Ok(rows)
        }

        async fn set_vt<'c, C, T, H>(
            executor: $ref_type!(C),
            queue_name: crate::types::QueueName<'_>,
            msg_ids: &[i64],
            visibility_timeout: crate::types::VisibilityTimeoutOffset,
        ) -> Result<Vec<crate::Message<T, H>>, crate::PgmqError>
        where
            C: $executor_trait,
            T: for<'de> serde::Deserialize<'de>,
            H: for<'de> serde::Deserialize<'de>,
        {
            let params: [crate::queue::rust_postgres::SqlParam; _] = [
                (&*queue_name, postgres_types::Type::TEXT),
                (&msg_ids, postgres_types::Type::INT8_ARRAY),
                (&*visibility_timeout, postgres_types::Type::INT4),
            ];
            let rows = executor.query_typed(crate::queue::sql::SET_VT, &params);
            let rows = $transform_result!(rows)?;
            rows.into_iter()
                .map(|row| crate::Message::<T, H>::try_from(row))
                .collect::<Result<Vec<crate::Message<T, H>>, crate::PgmqError>>()
        }

        async fn create_fifo_index<C>(
            executor: $ref_type!(C),
            queue_name: crate::types::QueueName<'_>,
        ) -> Result<(), crate::PgmqError>
        where
            C: $executor_trait,
        {
            let params: [crate::queue::rust_postgres::SqlParam; _] =
                [(&*queue_name, postgres_types::Type::TEXT)];
            let result = executor.execute_typed(crate::queue::sql::CREATE_FIFO_INDEX, &params);
            $transform_result!(result)?;
            Ok(())
        }

        async fn create_fifo_indexes_all<C>(executor: $ref_type!(C)) -> Result<(), crate::PgmqError>
        where
            C: $executor_trait,
        {
            let result = executor.execute_typed(crate::queue::sql::CREATE_FIFO_INDEXES_ALL, &[]);
            $transform_result!(result)?;
            Ok(())
        }

        async fn read_grouped<C, T, H>(
            executor: $ref_type!(C),
            queue_name: crate::types::QueueName<'_>,
            visibility_timeout: crate::types::VisibilityTimeoutOffset,
            quantity: i32,
        ) -> Result<Vec<crate::Message<T, H>>, crate::PgmqError>
        where
            C: $executor_trait,
            T: for<'de> serde::Deserialize<'de>,
            H: for<'de> serde::Deserialize<'de>,
        {
            read_common(
                executor,
                crate::queue::sql::READ_GROUPED,
                queue_name,
                visibility_timeout,
                quantity,
            )
            .await
        }

        async fn read_grouped_head<C, T, H>(
            executor: $ref_type!(C),
            queue_name: crate::types::QueueName<'_>,
            visibility_timeout: crate::types::VisibilityTimeoutOffset,
            quantity: i32,
        ) -> Result<Vec<crate::Message<T, H>>, crate::PgmqError>
        where
            C: $executor_trait,
            T: for<'de> serde::Deserialize<'de>,
            H: for<'de> serde::Deserialize<'de>,
        {
            read_common(
                executor,
                crate::queue::sql::READ_GROUPED_HEAD,
                queue_name,
                visibility_timeout,
                quantity,
            )
            .await
        }

        async fn read_grouped_rr<C, T, H>(
            executor: $ref_type!(C),
            queue_name: crate::types::QueueName<'_>,
            visibility_timeout: crate::types::VisibilityTimeoutOffset,
            quantity: i32,
        ) -> Result<Vec<crate::Message<T, H>>, crate::PgmqError>
        where
            C: $executor_trait,
            T: for<'de> serde::Deserialize<'de>,
            H: for<'de> serde::Deserialize<'de>,
        {
            read_common(
                executor,
                crate::queue::sql::READ_GROUPED_RR,
                queue_name,
                visibility_timeout,
                quantity,
            )
            .await
        }

        async fn read_common<C, T, H>(
            executor: $ref_type!(C),
            query: &'static str,
            queue_name: crate::types::QueueName<'_>,
            visibility_timeout: crate::types::VisibilityTimeoutOffset,
            quantity: i32,
        ) -> Result<Vec<crate::Message<T, H>>, crate::PgmqError>
        where
            C: $executor_trait,
            T: for<'de> serde::Deserialize<'de>,
            H: for<'de> serde::Deserialize<'de>,
        {
            let params: [crate::queue::rust_postgres::SqlParam; _] = [
                (&*queue_name, postgres_types::Type::TEXT),
                (&*visibility_timeout, postgres_types::Type::INT4),
                (&quantity, postgres_types::Type::INT4),
            ];
            let rows = executor.query_typed(query, &params);
            let rows = $transform_result!(rows)?;
            rows.into_iter()
                .map(|row| crate::Message::<T, H>::try_from(row))
                .collect::<Result<Vec<crate::Message<T, H>>, crate::PgmqError>>()
        }

        async fn bind_topic<C>(
            executor: $ref_type!(C),
            pattern: &str,
            queue_name: crate::types::QueueName<'_>,
        ) -> Result<(), crate::PgmqError>
        where
            C: $executor_trait,
        {
            let params: [crate::queue::rust_postgres::SqlParam; _] = [
                (&pattern, postgres_types::Type::TEXT),
                (&*queue_name, postgres_types::Type::TEXT),
            ];
            let result = executor.execute_typed(crate::queue::sql::BIND_TOPIC, &params);
            $transform_result!(result)?;
            Ok(())
        }

        async fn unbind_topic<C>(
            executor: $ref_type!(C),
            pattern: &str,
            queue_name: crate::types::QueueName<'_>,
        ) -> Result<(), crate::PgmqError>
        where
            C: $executor_trait,
        {
            let params: [crate::queue::rust_postgres::SqlParam; _] = [
                (&pattern, postgres_types::Type::TEXT),
                (&*queue_name, postgres_types::Type::TEXT),
            ];
            let result = executor.execute_typed(crate::queue::sql::UNBIND_TOPIC, &params);
            $transform_result!(result)?;
            Ok(())
        }

        async fn list_topic_bindings<C>(
            executor: $ref_type!(C),
            queue_name: crate::types::QueueName<'_>,
        ) -> Result<Vec<crate::types::ListTopicBindingsRow>, crate::PgmqError>
        where
            C: $executor_trait,
        {
            let params: [crate::queue::rust_postgres::SqlParam; _] =
                [(&*queue_name, postgres_types::Type::TEXT)];
            let rows = executor.query_typed(crate::queue::sql::LIST_TOPIC_BINDINGS, &params);
            let rows = $transform_result!(rows)?;
            let rows = rows
                .into_iter()
                .map(|row| crate::types::ListTopicBindingsRow::try_from(row))
                .collect::<Result<Vec<crate::types::ListTopicBindingsRow>, _>>()?;
            Ok(rows)
        }

        async fn list_topic_bindings_all<C>(
            executor: $ref_type!(C),
        ) -> Result<Vec<crate::types::ListTopicBindingsRow>, crate::PgmqError>
        where
            C: $executor_trait,
        {
            let rows = executor.query_typed(crate::queue::sql::LIST_TOPIC_BINDINGS_ALL, &[]);
            let rows = $transform_result!(rows)?;
            let rows = rows
                .into_iter()
                .map(|row| crate::types::ListTopicBindingsRow::try_from(row))
                .collect::<Result<Vec<crate::types::ListTopicBindingsRow>, _>>()?;
            Ok(rows)
        }

        async fn send_topic<C>(
            executor: $ref_type!(C),
            routing_key: &str,
            message: serde_json::Value,
            headers: serde_json::Value,
            delay: crate::types::VisibilityTimeoutOffset,
        ) -> Result<i32, crate::PgmqError>
        where
            C: $executor_trait,
        {
            let params: [crate::queue::rust_postgres::SqlParam; _] = [
                (&routing_key, postgres_types::Type::TEXT),
                (&message, postgres_types::Type::JSONB),
                (&headers, postgres_types::Type::JSONB),
                (&*delay, postgres_types::Type::INT4),
            ];
            let row = executor.query_typed_one(crate::queue::sql::SEND_TOPIC, &params);
            let row = $transform_result!(row)?;
            Ok(row.try_get(0)?)
        }

        async fn send_batch_topic<C>(
            executor: $ref_type!(C),
            routing_key: &str,
            messages: Vec<serde_json::Value>,
            headers: Option<Vec<serde_json::Value>>,
            delay: crate::types::VisibilityTimeoutOffset,
        ) -> Result<Vec<crate::types::SendBatchTopicRow>, crate::PgmqError>
        where
            C: $executor_trait,
        {
            let params: [crate::queue::rust_postgres::SqlParam; _] = [
                (&routing_key, postgres_types::Type::TEXT),
                (&messages, postgres_types::Type::JSONB_ARRAY),
                (&headers, postgres_types::Type::JSONB_ARRAY),
                (&*delay, postgres_types::Type::INT4),
            ];
            let rows = executor.query_typed(crate::queue::sql::SEND_BATCH_TOPIC, &params);
            let rows = $transform_result!(rows)?;
            let rows = rows
                .into_iter()
                .map(|row| crate::types::SendBatchTopicRow::try_from(row))
                .collect::<Result<Vec<crate::types::SendBatchTopicRow>, _>>()?;
            Ok(rows)
        }
    };
}
pub(crate) use rust_postgres_functions;
