name: PGMQ Extension

defaults:
  run:
    shell: bash
    working-directory: ./

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "pgmq-rs/**"
      - "tembo-pgmq-python/**"
  push:
    branches:
      - main
    paths-ignore:
      - "pgmq-rs/**"
      - "tembo-pgmq-python/**"
  release:
    types:
      - created

jobs:
  lint:
    name: Run linters for integration tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust minimal nightly with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "pgmq-extension-lint"
          workspaces: |
            pgmq/
      - name: Cargo format
        run: cargo +nightly fmt --manifest-path integration_test/Cargo.toml --all --check
      - name: Clippy
        run: cargo clippy --manifest-path integration_test/Cargo.toml

  test:
    name: Run tests
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        pg: [12, 13, 14, 15, 16]
    container: pgxn/pgxn-tools
    steps:
      - run: pg-start ${{ matrix.pg }}
      - uses: actions/checkout@v2
      - run: apt install -y pkg-config
      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "pgmq-extension-test-${{ matrix.pg }}"
          workspaces: |
            pgmq
      - name: Install pg_partman
        run: |
          git clone https://github.com/pgpartman/pg_partman.git && \
          cd pg_partman && \
          git checkout v4.7.4 && \
          make && \
          make install
      - run: pg-build-test

  publish:
    name: trunk publish
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        pg-version: [14, 15, 16]
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "pgmq-extension-test"
          workspaces: |
            pgmq/extension
      - name: Install stoml and pg-trunk
        shell: bash
        run: |
          set -xe
          wget https://github.com/freshautomations/stoml/releases/download/v0.7.1/stoml_linux_amd64 &> /dev/null
          mv stoml_linux_amd64 stoml
          chmod +x stoml
          sudo mv stoml /usr/local/bin/
          cargo install pg-trunk
      - name: Make trunk
        run: make Trunk.toml
      - name: trunk build
        working-directory: ./
        run: trunk build --pg-version ${{ matrix.pg-version }}
      - name: trunk publish
        # only publish release events
        if: github.event_name == 'release'
        working-directory: ./
        env:
          TRUNK_API_TOKEN: ${{ secrets.TRUNK_AUTH_TOKEN }}
        run: |
          pgmq_ver=$(stoml Cargo.toml package.version)
          pgmq_descr=$(stoml Cargo.toml package.description)
          pgmq_repo=$(stoml Cargo.toml package.repository)
          trunk publish pgmq --version ${pgmq_ver} --description "A lightweight message queue. Like AWS SQS and RSMQ, on Postgres." --homepage "https://github.com/tembo-io/pgmq" --repository "https://github.com/tembo-io/pgmq" --license "PostgreSQL" --category featured --category orchestration
  build_and_push:
    name: Build and push images
    # needs:
    #   - publish
    runs-on:
      - self-hosted
      - dind
      - large-8x8
    strategy:
      matrix:
        pg: [14, 15, 16]
    outputs:
      short_sha: ${{ steps.versions.outputs.SHORT_SHA }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Install stoml and pg-trunk
        shell: bash
        run: |
          set -xe
          wget https://github.com/freshautomations/stoml/releases/download/v0.7.1/stoml_linux_amd64 &> /dev/null
          mv stoml_linux_amd64 stoml
          chmod +x stoml
          sudo mv stoml /usr/local/bin/

      - name: Set version strings
        id: versions
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "TAG_VER=$(/usr/local/bin/stoml Cargo.toml package.version)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io/tembo
          username: ${{ secrets.QUAY_USER_TEMBO }}
          password: ${{ secrets.QUAY_PASSWORD_TEMBO }}

      - name: Generate dockerfile from template file
        run: ./images/pgmq-pg/replace-pg-version.sh ${{ matrix.pg }} ./images/pgmq-pg/Dockerfile.in ./images/pgmq-pg/Dockerfile

      - name: Build and push -- Commit
        # push commit build when not a release
        if: github.event_name != 'release'
        uses: docker/build-push-action@v5
        with:
          file: ./images/pgmq-pg/Dockerfile
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            quay.io/tembo/pg${{matrix.pg}}-pgmq:v${{ steps.versions.outputs.SHORT_SHA }}

      - name: Build and push -- Releases
        # only publish release events
        if: github.event_name == 'release'
        uses: docker/build-push-action@v5
        with:
          file: ./images/pgmq-pg/Dockerfile
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            quay.io/tembo/pg${{matrix.pg}}-pgmq:v${{ steps.versions.outputs.TAG_VER }}
            quay.io/tembo/pg${{matrix.pg}}-pgmq:latest
